apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls: 
  - hosts:
    - moimartoli.duckdns.org
    secretName: letsencrypt
  - hosts:
    - portfolio.martinezarranz.cat
    secretName: letsencryptp
  rules:
  - host: moimartoli.duckdns.org
    http:
      paths:
      - path: /odata
        pathType: Prefix
        backend:
          service:
            name: odata-svc
            port:
              number: 80
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: healthrust-svc
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-svc
            port:
              number: 80
  - host: portfolio.martinezarranz.cat
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-svc
            port:
              number: 80

#  tls:
#    - secretName: letsencrypt
#      hosts:
#        - moimartoli.duckdns.org

