apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portfolio-ingress-admin
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: portfolio-ingress
    # Reference to upper's `metadata.namespace`
    namespace: portfolio-ingress
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-cainjector-admin
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: cert-manager-cainjector
    # Reference to upper's `metadata.namespace`
    namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-admin
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: cert-manager
    # Reference to upper's `metadata.namespace`
    namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-admin
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: cert-manager-webhook
    # Reference to upper's `metadata.namespace`
    namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
